redis:
  address: "localhost"
  port: 6379
  credentials:
    password: "rabbit"
amq_source:
  broker:
    address: "localhost"
    port: 5672
  credentials:
    username: "admin"
    password: "rabbit"
amq_target:
  broker:
    address: localhost # 192.168.1.139
    port: 5673 # 5672
  credentials:
    username: "admin"
    password: "rabbit"
pub_sub:
  - pub_sub_1:
      source:
        exchange: "generator_robot"
        exchange_type: "fanout"
        queue: "generator_robot_rk"
      target:
        exchange: "generator_robot"
        exchange_type: "fanout"
        queue: "generator_robot_rk"
  - pub_sub_2:
      source:
        exchange: "generator_personnel"
        exchange_type: "fanout"
        queue: "generator_personnel_rk"
      target:
        exchange: "generator_personnel"
        exchange_type: "fanout"
        queue: "generator_personnel_rk"
